// GENERATED FILE - do not edit by hand.
// Generated by scripts/gen-types.mjs from schema/ (OpenBook 0.3.0-draft).
// The schema files are CC BY 4.0; see the repository NOTICE.
/* eslint-disable */

/** The OpenBook spec version these types were generated from. */
export const OPENBOOK_SPEC_VERSION = "0.3.0-draft";

// ------------------------------------------------------------------ common

export type OpenbookVersion = string;
export type Sequence = number;
export type DateTime = string;
export type DecimalString = string;
export type DecimalOdds = string | null;
export type Money = { amount: DecimalString; [x: string]: unknown; };
export type Iso4217 = string;
export type SharedId = string;
export type OwnId = string;
export type Territory = string;
export type SameAs = string | null;
export type Identifier = Array<{ propertyID: string; value: string; }>;
export type AlternateName = Array<string>;
export type LocalizedNames = Record<string, string>;
export type NameLatin = string;
export type Iso6391 = string;
export type TimeZone = string;
export type Latitude = number;
export type Longitude = number;
export type Place = { name?: string; shortName?: string; registeredName?: string; alternateName?: AlternateName; names?: LocalizedNames; nameLatin?: NameLatin; addressLocality?: string; territory?: Territory; timeZone?: TimeZone; latitude?: Latitude; longitude?: Longitude; sameAs?: SameAs; identifier?: Identifier; [x: string]: unknown; };
export type Surface = "grass" | "clay" | "hard" | "turf" | "ice" | "indoor" | "other";
export type Gender = "men" | "women" | "mixed" | "open" | "other";
export type AgeGroup = string;
export type Hand = "left" | "right" | "both";
export type Elected = "bat" | "bowl";
export type Side = "home" | "away" | "draw" | "over" | "under" | "yes" | "no" | "participant" | "other" | "odd" | "even" | "none" | "home-or-draw" | "away-or-draw" | "home-or-away";
export type HomeAwayDraw = "home" | "away" | "draw";
export type MarketOutcome = { side: Side; participant?: OwnId; odds?: DecimalOdds; line?: DecimalString; active?: boolean; homeTotal?: number; awayTotal?: number; halfTime?: HomeAwayDraw; fullTime?: HomeAwayDraw; player?: OwnId; atLeast?: number; [x: string]: unknown; };
export type GradeOutcome = { side: Side; participant?: OwnId; line?: DecimalString; result: GradeResult; homeTotal?: number; awayTotal?: number; halfTime?: HomeAwayDraw; fullTime?: HomeAwayDraw; player?: OwnId; atLeast?: number; };
export type Provenance = "official" | "licensed" | "observed";
export type Role = "home" | "away" | "neutral";
export type Deprecation = { name: string; reason: string; replacement: string; sunset: string; };
export type Jsonld = { "@context"?: unknown; "@type"?: string; };
export type ObjectType = "fixture" | "odds" | "market" | "score" | "grade" | "league" | "season" | "stage" | "participant" | "player" | "lineup" | "publisher" | "stall" | "toss" | "series";
export type Action = "snapshot" | "create" | "update" | "delete" | "change" | "snapshotComplete" | "heartbeat";
export type MsgType = "alert" | "update" | "cancel";
export type EventStatus = "scheduled" | "delayed" | "live" | "paused" | "suspended" | "postponed" | "ended" | "cancelled";
export type MarketStatus = "open" | "suspended" | "closed" | "void";
export type CompetitionType = "league" | "cup" | "tournament" | "series" | "exhibition";
export type ParticipantType = "team" | "individual";
export type SourceType = "sportsbook" | "exchange" | "model";
export type FeedKind = "snapshot" | "stream" | "docs" | "mcp" | "plugin";
export type StageType = "phase" | "group" | "round" | "matchday" | "leg" | "seriesGame";
export type MarketShape = "binary" | "n-way" | "over-under" | "handicap" | "exact-value" | "correct-score" | "yes-no" | "composite";
export type MarketCategory = "main-line" | "score-prop" | "game-prop" | "player-prop" | "outright" | "parlay-special" | "same-game-parlay";
export type SegmentStatus = "pending" | "live" | "paused" | "down";
export type StatusReason = "weather" | "crowd" | "injury" | "retirement" | "walkover" | "forfeit" | "technical" | "scheduling" | "correction" | "other";
export type ScoreUnit = "goals" | "points" | "runs" | "hits" | "errors" | "sets" | "games" | "frames" | "strokes" | "laps" | "position" | "time" | "corners" | "yellowCards" | "redCards" | "wickets" | "overs" | "rounds" | "knockdowns" | "aces" | "faults" | "other";
export type GradeResult = "win" | "lose" | "void" | "half-win" | "half-lose";

// ---------------------------------------------------------------- documents

export type ChangeEnvelope = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; sequence: Sequence; datePublished: DateTime; publisher: OwnId; object: ObjectType; action: Action; sport: string; id?: OwnId; msgType?: MsgType; reason?: string; references?: Array<Sequence>; conflated?: boolean; changes: Record<string, unknown>; [x: string]: unknown; };
export type Discovery = { lastUpdated: DateTime; ttl: number; feeds: Array<{ name: string; url: string; kind?: FeedKind; id?: OwnId; schemaUrl?: string; [x: string]: unknown; }>; [x: string]: unknown; };
export type Fixture = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; id: OwnId; sequence: Sequence; dateModified: DateTime; name?: string; sport: { id: SharedId; name: string; }; league: { id: OwnId; name: string; territory: Territory; competitionType: CompetitionType; shortName?: string; registeredName?: string; gender?: Gender; ageGroup?: AgeGroup; sameAs?: SameAs; }; season?: { id?: OwnId; name?: string; }; stage?: { id?: OwnId; name?: string; stageType?: StageType; }; startDate: DateTime; cutoffDate?: DateTime; eventStatus?: EventStatus; superEvent?: OwnId; participants: Array<{ id: OwnId; name: string; territory: Territory; role: Role; order: number; sameAs?: SameAs; seed?: number; }>; location?: Place; surface?: Surface; identifier?: Identifier; [x: string]: unknown; };
export type Grade = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; sequence: Sequence; dateModified: DateTime; gradeId: OwnId; supersedes?: OwnId; fixture: OwnId; segment: SharedId; source: OwnId; marketType: SharedId; line?: DecimalString; basis: ScoreUnit; basedOn: Sequence; dateGraded?: DateTime; outcomes: Array<GradeOutcome>; [x: string]: unknown; };
export type League = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; id: OwnId; sequence: Sequence; dateModified: DateTime; name: string; shortName?: string; registeredName?: string; alternateName?: AlternateName; names?: LocalizedNames; nameLatin?: NameLatin; gender?: Gender; ageGroup?: AgeGroup; sport: SharedId; territory: Territory; competitionType: CompetitionType; organizer?: { id?: OwnId; name?: string; sameAs?: SameAs; }; ruleset?: { clockBased?: boolean; clockAscending?: boolean; scoreBased?: boolean; segmentBased?: boolean; hasHalftime?: boolean; allowTies?: boolean; segments?: Array<SharedId>; primaryUnit?: ScoreUnit; }; limit?: Money; sameAs: SameAs; identifier?: Identifier; [x: string]: unknown; };
export type Lineup = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; sequence: Sequence; dateModified: DateTime; fixture: OwnId; player: Array<OwnId>; [x: string]: unknown; };
export type Market = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; sequence: Sequence; dateModified: DateTime; fixture: OwnId; marketType: SharedId; segment?: SharedId; line?: DecimalString; basis?: ScoreUnit; source: OwnId; provenance: Provenance; status: MarketStatus; isMain?: boolean; limit: Money; outcomes: Array<MarketOutcome>; [x: string]: unknown; };
export type MarketType = { id: string; name: string; genre: string; shape: MarketShape; category: MarketCategory; sides?: Array<Side>; sequence?: Sequence; dateModified?: DateTime; identifier?: Identifier; openbookVersion: OpenbookVersion; isPlayerProp?: boolean; isTeamProp?: boolean; isGameProp?: boolean; "@context"?: unknown; "@type"?: string; [x: string]: unknown; };
export type OddsChange = { markets: Array<{ segment?: SharedId; line?: DecimalString; basis?: ScoreUnit; status?: MarketStatus; limit?: Money; source: OwnId; provenance: Provenance; outcomes: Array<MarketOutcome>; marketType: SharedId; [x: string]: unknown; }>; [x: string]: unknown; };
export type Participant = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; id: OwnId; sequence: Sequence; dateModified: DateTime; participantType: ParticipantType; sport: SharedId; territory: Territory; name: string; shortName?: string; abbreviation?: string; location?: string; nickname?: string; registeredName?: string; alternateName?: AlternateName; names?: LocalizedNames; nameLatin?: NameLatin; familyName?: string; givenName?: string; sameAs: SameAs; identifier?: Identifier; [x: string]: unknown; };
export type Player = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; sequence: Sequence; dateModified: DateTime; id: OwnId; participant: OwnId; team: OwnId; position?: string; number?: number; throws?: Hand; bats?: Hand; startDate?: DateTime; endDate?: DateTime; active?: boolean; identifier?: Identifier; [x: string]: unknown; };
export type Publisher = { id: string; sequence: Sequence; name: string; registeredName?: string; inLanguage?: Iso6391; baseCurrency: Iso4217; url?: string; sources: Array<{ id: OwnId; name: string; territory?: Territory; url?: string; sourceType: SourceType; sameAs?: SameAs; }>; openbookVersion: OpenbookVersion; dateModified: DateTime; email?: string; heartbeatMs?: number; ttl?: number; "@context"?: unknown; "@type"?: string; [x: string]: unknown; };
export type Region = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; id: Territory; sequence: Sequence; dateModified: DateTime; name: string; names?: LocalizedNames; parent?: Territory; iocCode?: string | null; fifaCode?: string | null; sameAs?: SameAs; identifier?: Identifier; [x: string]: unknown; };
export type Score = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; sequence: Sequence; dateModified: DateTime; fixture: OwnId; eventStatus: EventStatus; statusReason?: StatusReason; correction?: boolean; segments: Array<{ segment: SharedId; status: SegmentStatus; downAt?: DateTime; order?: number; }>; currentSegment?: SharedId; clock?: { elapsed?: number; remaining?: number; running?: boolean; display?: string; }; scores: Array<{ participant: OwnId; unit: ScoreUnit; total: number; bySegment?: Record<string, number>; display?: string; }>; server?: OwnId; [x: string]: unknown; };
export type Season = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; sequence: Sequence; dateModified: DateTime; id: OwnId; league: OwnId; name: string; alternateName?: AlternateName; startDate?: DateTime; endDate?: DateTime; sameAs?: SameAs; identifier?: Identifier; [x: string]: unknown; };
export type Series = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; sequence: Sequence; dateModified: DateTime; fixture: OwnId; stage: OwnId; wins: Array<{ participant: OwnId; total: number; }>; needed?: number; [x: string]: unknown; };
export type Sport = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; id: SharedId; name: string; abbreviation?: string; active?: boolean; alternateName?: AlternateName; names?: LocalizedNames; sameAs?: SameAs; identifier?: Identifier; primaryUnit?: ScoreUnit; limit?: Money; [x: string]: unknown; };
export type Stage = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; id: OwnId; sequence: Sequence; dateModified: DateTime; season: OwnId; name: string; alternateName?: AlternateName; parent?: OwnId; stageType: StageType; order?: number; startDate?: DateTime; endDate?: DateTime; identifier?: Identifier; [x: string]: unknown; };
export type Stall = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; id: OwnId; sequence: Sequence; dateModified: DateTime; fixture: OwnId; participant: OwnId; order: number; [x: string]: unknown; };
export type Toss = { "@context"?: unknown; "@type"?: string; openbookVersion: OpenbookVersion; id: OwnId; sequence: Sequence; dateModified: DateTime; fixture: OwnId; participant: OwnId; elected: Elected; [x: string]: unknown; };
